'use strict';

/*
 * a1panel — AI-native server operations panel.
 *
 * Model:
 *   - Password login gate (initial password shown once, then only a hash is kept).
 *   - LLM connection: custom Base URL + API key + model (Anthropic Messages-API compatible).
 *   - Left sidebar of operations MODULES (概览 / Docker / 网站与证书 / 进程 / 服务 / ...).
 *     A module is generated by the model ONLY when the user first opens it (lazy),
 *     then persisted forever (modules.json). Each module is a full operational page:
 *       collect(ctx)          -> read system data (server-side)
 *       actions[name](ctx)    -> PERFORM an operation (restart/kill/renew/clean...)
 *       render(data)          -> full-page HTML (browser); buttons carry data-action
 */

const http = require('http');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const fsp = require('fs/promises');
const fs = require('fs');
const { exec: cpExec } = require('child_process');

const PORT = Number(process.env.A1_PORT || 7070);
const HOST = process.env.A1_HOST || '127.0.0.1';
const ROOT = __dirname;
const PUBLIC_DIR = path.join(ROOT, 'public');
const MODULES_FILE = path.join(ROOT, 'modules.json');
const AUTH_FILE = path.join(ROOT, 'auth.json');

const API_VERSION = '2023-06-01';
const DEFAULT_BASE_URL = 'https://api.anthropic.com';

// ---------------------------------------------------------------------------
// Sidebar preset modules. These are just the MENU — nothing is generated until
// the user clicks one. `brief` steers the generation toward an operational page.
// ---------------------------------------------------------------------------
const PRESETS = [
  { id: 'overview', title: '概览', brief: '全机概览仪表盘头部：主机名、操作系统、运行时长、CPU 负载、内存使用、各磁盘容量、网络关键指标，用多列大号数字 + 进度条呈现，像专业运维面板首页。可提供“刷新”操作。' },
  { id: 'docker', title: 'Docker', brief: '容器与镜像管理：列出所有容器(名称/状态/镜像/端口)与镜像列表；每个容器提供 启动/停止/重启/删除/查看日志 操作按钮(data-action，破坏性操作加 data-confirm)。用 `docker ps -a --format`、`docker images`、`docker start|stop|restart|rm`、`docker logs --tail 200`。若未安装或不可用，展示清晰的“未检测到 Docker”空状态而不是报错。' },
  { id: 'web', title: '网站与证书', brief: '网站与 TLS 证书：尽力列出本机网站/反向代理(优先 `nginx -T` 或常见站点目录)与已安装证书及到期天数(可用 openssl 读取 .pem/.crt 或扫描常见证书目录)；提供 重载 nginx、证书续期(若有 certbot 则 `certbot renew`) 等操作。无相关组件时展示“未检测到”空状态。' },
  { id: 'process', title: '进程', brief: '进程管理：按内存(或 CPU)排序列出 Top 15 进程(PID/名称/内存/CPU)，每行提供 结束进程 操作(data-action + data-confirm)。Windows 用 `Get-Process`/`Stop-Process`，Linux 用 ps/kill。' },
  { id: 'service', title: '服务', brief: '服务管理：列出关键/运行中服务及状态，每项提供 启动/停止/重启 操作。Windows 用 `Get-Service`/`Start-Service`/`Restart-Service`，Linux 用 systemctl。' },
  { id: 'network', title: '网络与端口', brief: '网络与监听端口：列出监听端口(端口/协议/占用进程)、网卡与 IP、连接数概览；可提供 结束占用端口的进程 操作。Windows 用 `Get-NetTCPConnection`/netstat，Linux 用 ss/netstat。' },
  { id: 'disk', title: '磁盘与文件', brief: '磁盘与清理：各分区容量与使用率进度条；列出占用较大的目录或临时文件；提供 清理临时目录 等操作(带确认)。' },
  { id: 'cron', title: '计划任务', brief: '计划任务：列出计划/定时任务及状态，提供 启用/禁用/立即运行 操作。Windows 用 `Get-ScheduledTask`/schtasks，Linux 用 `crontab -l` 与 systemd timers。' },
  { id: 'logs', title: '系统日志', brief: '系统日志：展示最近的系统/错误日志条目(可分级、可筛选)，提供 刷新 操作。Windows 用 `Get-WinEvent`/`Get-EventLog`，Linux 用 journalctl 或 /var/log。以只读为主。' },
];

// ---------------------------------------------------------------------------
// Panel auth (login password) — deterministic security boundary.
// ---------------------------------------------------------------------------
let auth = null;
const sessions = new Set();

function hashPw(pw, salt) {
  return crypto.scryptSync(String(pw), salt, 32).toString('hex');
}
function initAuth() {
  try {
    auth = JSON.parse(fs.readFileSync(AUTH_FILE, 'utf8'));
    return;
  } catch {
    /* first run */
  }
  const salt = crypto.randomBytes(16).toString('hex');
  const pw = crypto.randomBytes(12).toString('base64url');
  auth = { salt, hash: hashPw(pw, salt), revealed: false, initial: pw };
  fs.writeFileSync(AUTH_FILE, JSON.stringify(auth, null, 2));
  console.log('');
  console.log('  ┌───────────────────────────────────────────────────────────┐');
  console.log('  │  a1panel 初始登录密码（仅显示这一次，请妥善保存）：        │');
  console.log('  │                                                           │');
  console.log('  │     ' + pw + ' '.repeat(Math.max(0, 21 - pw.length)) + '  │');
  console.log('  │                                                           │');
  console.log('  │  登录后此密码将不再显示；如需重置请删除 auth.json 重启。   │');
  console.log('  └───────────────────────────────────────────────────────────┘');
}
function consumeReveal() {
  if (auth && !auth.revealed && auth.initial) {
    const pw = auth.initial;
    auth.revealed = true;
    delete auth.initial;
    fsp.writeFile(AUTH_FILE, JSON.stringify(auth, null, 2)).catch(() => {});
    return pw;
  }
  return null;
}
function verifyPassword(pw) {
  if (!auth) return false;
  const cand = Buffer.from(hashPw(pw, auth.salt), 'hex');
  const good = Buffer.from(auth.hash, 'hex');
  return cand.length === good.length && crypto.timingSafeEqual(cand, good);
}
function parseCookies(req) {
  const out = {};
  (req.headers.cookie || '').split(';').forEach((p) => {
    const i = p.indexOf('=');
    if (i > 0) out[p.slice(0, i).trim()] = decodeURIComponent(p.slice(i + 1).trim());
  });
  return out;
}
function isAuthed(req) {
  const c = parseCookies(req);
  return !!(c.a1session && sessions.has(c.a1session));
}

// ---------------------------------------------------------------------------
// LLM connection state (never persisted).
// ---------------------------------------------------------------------------
const session = { apiKey: null, model: 'claude-sonnet-5', baseUrl: DEFAULT_BASE_URL };

/** modules: id -> { id, title, category, refreshMs, collect, actions:{name:code}, render, createdAt } */
let modules = new Map();

function loadModules() {
  try {
    const arr = JSON.parse(fs.readFileSync(MODULES_FILE, 'utf8'));
    if (Array.isArray(arr)) modules = new Map(arr.map((m) => [m.id, m]));
  } catch {
    /* none yet */
  }
}
function saveModules() {
  fsp
    .writeFile(MODULES_FILE, JSON.stringify([...modules.values()], null, 2))
    .catch((e) => console.error('persist modules:', e.message));
}
function moduleMeta(m) {
  return {
    id: m.id,
    title: m.title,
    category: m.category || '',
    refreshMs: m.refreshMs,
    actions: Object.keys(m.actions || {}),
    generated: true,
    createdAt: m.createdAt,
  };
}
function moduleFull(m) {
  return { ...moduleMeta(m), render: m.render };
}

// ---------------------------------------------------------------------------
// Execute AI-written code on the server (collect + actions).
// Single-user localhost admin tool: model-written code runs with the server's
// privileges by design (that is how it reads AND operates the machine).
// ---------------------------------------------------------------------------
const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;

function makeExec() {
  return (cmd, opts = {}) =>
    new Promise((resolve, reject) => {
      cpExec(
        cmd,
        { timeout: 12000, maxBuffer: 16 * 1024 * 1024, windowsHide: true, encoding: 'utf8', ...opts },
        (err, stdout, stderr) => {
          if (err && err.killed) return reject(new Error('command timed out: ' + cmd));
          resolve({
            stdout: String(stdout || ''),
            stderr: String(stderr || ''),
            code: err ? (typeof err.code === 'number' ? err.code : 1) : 0,
          });
        }
      );
    });
}

async function runFn(code, extra = {}, timeoutMs = 20000) {
  const c = String(code || '').trim();
  if (!c) throw new Error('no code');
  const helpers = { os, fs: fsp, path, platform: process.platform, exec: makeExec(), ...extra };
  const runner = new AsyncFunction('ctx', `"use strict"; const fn = (${c}); return await fn(ctx);`);
  const start = Date.now();
  let timer;
  const timeout = new Promise((_, rej) => {
    timer = setTimeout(() => rej(new Error('执行超时（' + timeoutMs + 'ms）')), timeoutMs);
  });
  try {
    const data = await Promise.race([runner(helpers), timeout]);
    return { data, ms: Date.now() - start };
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// LLM helpers (Base URL configurable).
// ---------------------------------------------------------------------------
async function llmFetch(pathname, body, { stream } = {}) {
  if (!session.apiKey) throw httpError(401, '未连接 LLM：请先填写 API Key');
  const base = session.baseUrl.replace(/\/+$/, '');
  return fetch(base + pathname, {
    method: 'POST',
    headers: {
      'x-api-key': session.apiKey,
      'anthropic-version': API_VERSION,
      'content-type': 'application/json',
    },
    body: JSON.stringify(stream ? { ...body, stream: true } : body),
  });
}

async function streamJSON({ system, user, schema, maxTokens = 12000, onEvent }) {
  const res = await llmFetch(
    '/v1/messages',
    {
      model: session.model,
      max_tokens: maxTokens,
      system,
      messages: [{ role: 'user', content: user }],
      output_config: { format: { type: 'json_schema', schema } },
    },
    { stream: true }
  );
  if (!res.ok || !res.body) {
    const t = await res.text().catch(() => '');
    let msg;
    try {
      msg = JSON.parse(t)?.error?.message;
    } catch {
      /* ignore */
    }
    throw httpError(res.status === 401 ? 401 : 502, `LLM ${res.status}: ${msg || res.statusText}`);
  }
  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buf = '';
  let full = '';
  let stopReason = null;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    let nl;
    while ((nl = buf.indexOf('\n')) >= 0) {
      const line = buf.slice(0, nl).trim();
      buf = buf.slice(nl + 1);
      if (!line.startsWith('data:')) continue;
      const payload = line.slice(5).trim();
      if (!payload) continue;
      let ev;
      try {
        ev = JSON.parse(payload);
      } catch {
        continue;
      }
      if (ev.type === 'content_block_delta') {
        const d = ev.delta || {};
        if (d.type === 'text_delta' && d.text) {
          full += d.text;
          onEvent && onEvent({ t: 'text', d: d.text });
        } else if (d.type === 'thinking_delta' && d.thinking) {
          onEvent && onEvent({ t: 'thinking', d: d.thinking });
        }
      } else if (ev.type === 'message_delta' && ev.delta && ev.delta.stop_reason) {
        stopReason = ev.delta.stop_reason;
      } else if (ev.type === 'error') {
        throw httpError(502, 'LLM stream error: ' + (ev.error?.message || 'unknown'));
      }
    }
  }
  if (stopReason === 'refusal') throw httpError(422, '模型出于安全策略拒绝了该请求，请换个说法重试。');
  try {
    return JSON.parse(full);
  } catch {
    throw httpError(502, '模型返回的 JSON 无法解析。');
  }
}

async function validateConnection() {
  const res = await llmFetch('/v1/messages', {
    model: session.model,
    max_tokens: 8,
    messages: [{ role: 'user', content: 'ping' }],
  });
  if (!res.ok) {
    const t = await res.text().catch(() => '');
    let msg;
    try {
      msg = JSON.parse(t)?.error?.message;
    } catch {
      /* ignore */
    }
    throw httpError(res.status === 401 ? 401 : 502, `LLM ${res.status}: ${msg || res.statusText}`);
  }
}

// ---------------------------------------------------------------------------
// Prompt
// ---------------------------------------------------------------------------
function moduleSystem() {
  const win = process.platform === 'win32';
  return `You are the generation engine behind "a1panel", an AI-native server OPERATIONS panel
(think 1Panel / Cockpit — you DO things, not just show metrics). You generate one MODULE at a
time. A module is a full operational page with three parts, all as JS source strings:

1) collect — async (ctx) => <JSON-serializable data>. Runs on the SERVER (Node.js).
   ctx = { os, fs, path, platform, exec }
     - exec(cmd) -> { stdout, stderr, code }. Never rejects on non-zero exit. 12s/command.
       On this host commands run via ${win ? 'cmd.exe (use `powershell -NoProfile -Command "..."` for structured output — add `| ConvertTo-Json -Compress`)' : '/bin/sh'}.
   Read the data the page needs (lists of containers/services/processes/ports/certs/disks...).
   Be defensive: if a tool is absent (e.g. docker/nginx/systemctl not installed), return
   { available:false, note:'...' } instead of throwing.

2) actions — an array of { name, code }. Each code is: async (ctx) => <result>.
   ctx = { os, fs, path, platform, exec, args }  (args = the button's data-args object)
   These PERFORM operations: start/stop/restart a service or container, kill a process,
   renew a cert, reload nginx, clean a temp dir, run a scheduled task, etc.
   Return a short human-readable result string (or object). Keep it bounded (≈20s).
   May be an empty array for read-only modules (e.g. logs).

3) render — (data) => "<html string>". Runs in the BROWSER. Returns the FULL page body.
   - Inline styles only. No external URLs/scripts/images/fonts. NO EMOJI anywhere.
   - LIGHT warm "Claude" theme: text #1f1e1d, muted #6b6862, accent #c96442, good #3d8a5f,
     warn #b7791f, bad #bc4b39, hairlines #e7e4db, subtle fill #f3f1ea, card #ffffff.
   - Make it look like a real ops panel: a summary row of headline numbers, then dense
     tables/lists with a status column and, where relevant, PER-ROW operation buttons.
   - Operation buttons MUST use this exact contract so the panel can execute them:
       <button data-action="ACTION_NAME" data-args='{"id":"..."}' data-confirm="确定重启 X？">重启</button>
     data-action = a name present in the actions array. data-args = a JSON object (single-quote
     the attribute so inner JSON uses double quotes). data-confirm is optional; include it for
     destructive actions. After an action runs the panel re-runs collect and re-renders.
   - Guard against missing/partial data; if data.available === false, render a clean empty state
     ("未检测到 …") instead of an error.

Host: ${os.type()} ${os.release()} (${os.arch()}), ${os.cpus().length} CPU, hostname ${os.hostname()}, Node ${process.version}, platform ${process.platform}.
${
  win
    ? `Windows notes: os.loadavg() is [0,0,0] (don't use it). PowerShell for structured data:
  memory os.totalmem/os.freemem; disks Get-CimInstance Win32_LogicalDisk; processes Get-Process;
  services Get-Service; ports Get-NetTCPConnection; tasks Get-ScheduledTask; events Get-WinEvent.
  docker/nginx/certbot are often NOT installed — detect and show an empty state.`
    : `Linux notes: os.loadavg(); ps/kill; systemctl; ss/netstat; df -kP; crontab -l; journalctl;
  docker/nginx/certbot may not be installed — detect and show an empty state.`
}
Return ONLY through the provided JSON schema. Titles/labels in Chinese, no emoji.`;
}

const MODULE_SCHEMA = {
  type: 'object',
  properties: {
    id: { type: 'string', description: 'kebab-case id' },
    title: { type: 'string', description: 'short Chinese module title' },
    category: { type: 'string', description: 'short Chinese category word, optional' },
    refreshMs: { type: 'integer', description: 'auto-refresh interval ms; 0 to disable; typical 4000-30000' },
    collect: { type: 'string', description: 'async (ctx) => data' },
    actions: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          code: { type: 'string', description: 'async (ctx) => result   (ctx.args holds the button payload)' },
        },
        required: ['name', 'code'],
        additionalProperties: false,
      },
    },
    render: { type: 'string', description: '(data) => "<html>"' },
  },
  required: ['id', 'title', 'refreshMs', 'collect', 'actions', 'render'],
  additionalProperties: false,
};

async function generateModule({ presetId, prompt, hint, keepId, onEvent }) {
  const preset = PRESETS.find((p) => p.id === presetId);
  let user;
  if (preset) {
    user = `Build the "${preset.title}" module.\n目标：${preset.brief}\n`;
  } else if (prompt) {
    user = `Build ONE operations module for this request:\n"""${prompt}"""\n`;
  } else {
    user = `Build ONE genuinely useful operations module for this machine.`;
  }
  if (hint) user += `\n用户对上一版不满意，请据此改进并做出明显不同：“${hint}”。\n`;
  user += `\nWrite complete, working collect / actions / render. Operational (real per-row buttons where it makes sense). No emoji. Return via the schema.`;

  const raw = await streamJSON({ system: moduleSystem(), user, schema: MODULE_SCHEMA, onEvent });

  const id = keepId || (preset && preset.id) || (typeof raw.id === 'string' && raw.id.trim()) || 'mod-' + Math.random().toString(36).slice(2, 8);
  let refreshMs = Number.isFinite(raw.refreshMs) ? Math.max(0, Math.min(raw.refreshMs, 3600000)) : 8000;
  if (refreshMs && refreshMs < 2000) refreshMs = 2000;
  const actions = {};
  for (const a of Array.isArray(raw.actions) ? raw.actions : []) {
    if (a && a.name && a.code) actions[String(a.name)] = String(a.code);
  }
  return {
    id,
    title: String(raw.title || (preset ? preset.title : '未命名模块')),
    category: String(raw.category || ''),
    refreshMs,
    collect: String(raw.collect || ''),
    actions,
    render: String(raw.render || ''),
    createdAt: Date.now(),
  };
}

// ---------------------------------------------------------------------------
// HTTP framework
// ---------------------------------------------------------------------------
function httpError(status, message) {
  const e = new Error(message);
  e.status = status;
  return e;
}
function sendJSON(res, status, obj, headers = {}) {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', ...headers });
  res.end(JSON.stringify(obj));
}
function startStream(res) {
  res.writeHead(200, {
    'content-type': 'application/x-ndjson; charset=utf-8',
    'cache-control': 'no-cache, no-transform',
    connection: 'keep-alive',
    'x-accel-buffering': 'no',
  });
  return {
    send(obj) {
      try {
        res.write(JSON.stringify(obj) + '\n');
      } catch {
        /* client gone */
      }
    },
    end() {
      try {
        res.end();
      } catch {
        /* ignore */
      }
    },
  };
}
function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (c) => {
      data += c;
      if (data.length > 4 * 1024 * 1024) reject(httpError(413, 'Body too large'));
    });
    req.on('end', () => {
      if (!data) return resolve({});
      try {
        resolve(JSON.parse(data));
      } catch {
        reject(httpError(400, 'Invalid JSON body'));
      }
    });
    req.on('error', reject);
  });
}
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json; charset=utf-8',
};
async function serveStatic(req, res, urlPath) {
  let rel = urlPath === '/' ? '/index.html' : urlPath;
  rel = decodeURIComponent(rel).replace(/\?.*$/, '');
  const filePath = path.normalize(path.join(PUBLIC_DIR, rel));
  if (!filePath.startsWith(PUBLIC_DIR)) return void res.writeHead(403).end('Forbidden');
  try {
    const buf = await fsp.readFile(filePath);
    res.writeHead(200, { 'content-type': MIME[path.extname(filePath)] || 'application/octet-stream' });
    res.end(buf);
  } catch {
    res.writeHead(404).end('Not found');
  }
}

// ---------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------
async function handleApi(req, res, url) {
  const { pathname } = url;
  const method = req.method;

  if (pathname === '/api/bootstrap' && method === 'GET') {
    const authed = isAuthed(req);
    const body = { authed };
    if (!authed) {
      const reveal = consumeReveal();
      if (reveal) body.initialPassword = reveal;
    }
    return sendJSON(res, 200, body);
  }
  if (pathname === '/api/login' && method === 'POST') {
    const b = await readBody(req);
    if (!verifyPassword(String(b.password || ''))) throw httpError(401, '密码错误');
    const token = crypto.randomBytes(24).toString('base64url');
    sessions.add(token);
    return sendJSON(res, 200, { authed: true }, {
      'set-cookie': `a1session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`,
    });
  }
  if (pathname === '/api/panel-logout' && method === 'POST') {
    const c = parseCookies(req);
    if (c.a1session) sessions.delete(c.a1session);
    return sendJSON(res, 200, { authed: false }, {
      'set-cookie': 'a1session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0',
    });
  }

  if (!isAuthed(req)) throw httpError(401, '需要登录');

  if (pathname === '/api/state' && method === 'GET') {
    return sendJSON(res, 200, {
      connected: !!session.apiKey,
      model: session.model,
      baseUrl: session.baseUrl,
      host: os.hostname(),
      platform: process.platform,
      presets: PRESETS.map((p) => ({ id: p.id, title: p.title })),
      modules: [...modules.values()].map(moduleMeta),
    });
  }

  if (pathname === '/api/session' && method === 'POST') {
    const b = await readBody(req);
    const key = String(b.apiKey || '').trim();
    const model = String(b.model || '').trim();
    const baseUrl = String(b.baseUrl || DEFAULT_BASE_URL).trim() || DEFAULT_BASE_URL;
    if (!/^https?:\/\//i.test(baseUrl)) throw httpError(400, 'Base URL 需以 http(s):// 开头');
    if (!key) throw httpError(400, '请填写 API Key');
    if (!model) throw httpError(400, '请填写模型名称');
    session.apiKey = key;
    session.model = model;
    session.baseUrl = baseUrl;
    try {
      await validateConnection();
    } catch (e) {
      session.apiKey = null;
      throw e;
    }
    return sendJSON(res, 200, { connected: true, model, baseUrl });
  }
  if (pathname === '/api/disconnect' && method === 'POST') {
    session.apiKey = null;
    return sendJSON(res, 200, { connected: false });
  }

  // ---- Modules ----
  // Create (generate) a module — streamed.
  if (pathname === '/api/module' && method === 'POST') {
    if (!session.apiKey) throw httpError(401, '未连接 LLM：请先填写 API Key');
    const b = await readBody(req);
    const stream = startStream(res);
    try {
      const mod = await generateModule({
        presetId: b.presetId,
        prompt: b.prompt,
        hint: b.hint,
        keepId: b.keepId || b.presetId || undefined,
        onEvent: (e) => stream.send(e),
      });
      modules.set(mod.id, mod);
      saveModules();
      stream.send({ t: 'done', module: moduleFull(mod) });
    } catch (e) {
      stream.send({ t: 'error', e: String(e.message || e) });
    }
    return stream.end();
  }

  const m = pathname.match(/^\/api\/module\/([^/]+)(?:\/(run|action|regenerate))?$/);
  if (m) {
    const id = decodeURIComponent(m[1]);
    const sub = m[2];

    if (!sub && method === 'GET') {
      const mod = modules.get(id);
      if (!mod) throw httpError(404, 'module not found');
      return sendJSON(res, 200, { module: moduleFull(mod) });
    }
    if (!sub && method === 'DELETE') {
      modules.delete(id);
      saveModules();
      return sendJSON(res, 200, { ok: true });
    }
    if (sub === 'run' && method === 'GET') {
      const mod = modules.get(id);
      if (!mod) throw httpError(404, 'module not found');
      try {
        const { data, ms } = await runFn(mod.collect, {}, 20000);
        return sendJSON(res, 200, { ok: true, data, ms });
      } catch (e) {
        return sendJSON(res, 200, { ok: false, error: String(e.message || e) });
      }
    }
    if (sub === 'action' && method === 'POST') {
      const mod = modules.get(id);
      if (!mod) throw httpError(404, 'module not found');
      const b = await readBody(req);
      const name = String(b.name || '');
      const code = mod.actions && mod.actions[name];
      if (!code) throw httpError(404, '未知操作：' + name);
      try {
        const { data, ms } = await runFn(code, { args: b.args || {} }, 25000);
        return sendJSON(res, 200, { ok: true, result: data, ms });
      } catch (e) {
        return sendJSON(res, 200, { ok: false, error: String(e.message || e) });
      }
    }
    if (sub === 'regenerate' && method === 'POST') {
      if (!session.apiKey) throw httpError(401, '未连接 LLM：请先填写 API Key');
      const b = await readBody(req);
      const prev = modules.get(id);
      const isPreset = PRESETS.some((p) => p.id === id);
      const stream = startStream(res);
      try {
        const mod = await generateModule({
          presetId: isPreset ? id : undefined,
          prompt: !isPreset ? (prev ? prev.title : undefined) : undefined,
          hint: b.hint || undefined,
          keepId: id,
          onEvent: (e) => stream.send(e),
        });
        if (prev && prev.category && !mod.category) mod.category = prev.category;
        modules.set(id, mod);
        saveModules();
        stream.send({ t: 'done', module: moduleFull(mod) });
      } catch (e) {
        stream.send({ t: 'error', e: String(e.message || e) });
      }
      return stream.end();
    }
  }

  throw httpError(404, 'Unknown API route');
}

// ---------------------------------------------------------------------------
const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  try {
    if (url.pathname.startsWith('/api/')) await handleApi(req, res, url);
    else await serveStatic(req, res, url.pathname);
  } catch (e) {
    const status = e.status || 500;
    if (!res.headersSent) sendJSON(res, status, { error: String(e.message || e) });
    else res.end();
    if (status >= 500) console.error(e);
  }
});

initAuth();
loadModules();
server.listen(PORT, HOST, () => {
  console.log('');
  console.log('  a1panel — AI 运维面板');
  console.log('  ▶  http://' + HOST + ':' + PORT);
  console.log('  已保存 ' + modules.size + ' 个模块。点开左侧菜单，AI 会在首次打开时生成并永久保留。');
  console.log('');
});
